### ISSUE TITLE
autoload vr/isearch-backward and vr/isearch-forward

### ISSUE THREAD

**Issue by thdox** [benma/visual-regexp-steroids.el#10]
Hello, is there any reason to *not* autoload vr/isearch-backward and vr/isearch-forward. I would like to bind a keyboard shortcut to these, but as they are not autoloaded, I cannot bind. I can propose simple Pull Request to add the autoload keyword to vr/isearch-backward and vr/isearch-forward, but I was wondering if there is any intention to *not* autoload?

I know that I can require in my .emacs the package before binding, but I do not want for performance reasons.

**Comment by benma** [comment]
No reason at all. I added it here: 7b362addac0ac9f988b01b400d3437ea82f52d1f

Let me know if it works for you.
