### ISSUE TITLE
reference to free variable `regexp-string'

### ISSUE THREAD

**Issue by brunoqc** [benma/visual-regexp-steroids.el#11]
I get these warnings in the `*Compile-log*` buffer when I start Emacs.

```
~/.emacs.d/elpa/visual-regexp-steroids-20150411.416/visual-regexp-steroids.elc:Warning:
    reference to free variable `regexp-string'
~/.emacs.d/elpa/visual-regexp-steroids-20150411.416/visual-regexp-steroids.elc:Warning:
    reference to free variable `replace-string'
```

**Comment by muyinliu** [comment]
Should add some line to visual-regexp.el:
```lisp
(defvar regexp-string nil)
(defvar replace-string nil)
```

**Comment by benma** [comment]
Should be fixed now (https://github.com/benma/visual-regexp.el/commit/b625cec147dd1ac185aac52e2ae27acb2a662b28), see the new update on melpa.

Please reopen if this does not fix it for you.
