### ISSUE TITLE
Incompatible with use-package?

### ISSUE THREAD

**Issue by alamaison** [benma/visual-regexp-steroids.el#16]
Thanks for creating the visual-regexp.* packages! I've been looking for something like this for ages and couldn't find anything like it.  Then stumbled across this from Awesome Emacs.

Now to the issue ... I use `use-package` to manage my `init.el` and I've never had a problem before, but it didn't work well with `visual-regexp-steroids`.  With the following, I would only get visual-regexp behaviour:

```elisp
(use-package visual-regexp-steroids
  :ensure
  :bind (("C-M-r" . vr/isearch-backward)
         ("C-M-s" . vr/isearch-forward)
         ("C-M-%" . vr/query-replace)))
```

I believe the underlying problem is that `use-package` requires the packages dependencies before the package and `visual-regexp-steroids` doesn't work if `visual-regexp` has previously been required.  Does this make sense?

I was able to work around the problem by explicitly deferring `visual-regexp` and explicitly demanding `visual-regexp-steroids`:
```elisp
(use-package visual-regexp
  :defer)

(use-package visual-regexp-steroids
  :ensure
  :demand
  :bind (("C-M-r" . vr/isearch-backward)
         ("C-M-s" . vr/isearch-forward)
         ("C-M-%" . vr/query-replace)))
```

**Comment by benma** [comment]
Sorry for the delay.

I don't use `use-package`, and I did not have time yet to look into how `use-package` works and reproduce this problem.

>I believe the underlying problem is that use-package requires the packages dependencies before the package and visual-regexp-steroids doesn't work if visual-regexp has previously been required. Does this make sense?

visual-regexp-steroids already internally requires visual-regexp, so there should not be a need to add `(use-package visual-regexp ...)` in the first place. 
The [installation instructions](https://github.com/benma/visual-regexp-steroids.el/#installation) also do not say anything about having to require visual-regexp.

Please try simply removing it.

**Comment by alamaison** [comment]
Thanks for the response.

The only reason I added `(use-package visual-regexp :defer)` was to *suppress* `use-package` requiring visual-regexp before it required visual-regexp-steroids.  However, if you say the latter includes the former anyway, that's can't have been the problem.  For the moment, I've switched to plain-old require.

**Comment by priyadarshan** [comment]
I do use `visual-regexp-steroids` with `use-package` myself with no issues.

My setup, in this case, is taken from [Silex's](https://github.com/Silex/emacs-config/blob/8432031819bf6a0f17bd30265f972d6dbc85ae9a/config/visual-regexp.el).

**Comment by benma** [comment]
Thanks! I wonder why visual-regexp is loaded explicitly.

`(require 'visual-regexp-steroids)` alone is enough, as that package loads `visual-regexp`. So the use-package equivalent of that should not have to load visual-regexp either. But I have no experience with use-package, so I might be wrong.

**Comment by priyadarshan** [comment]
You are right. It is not needed per se, only he may be using that as a skeleton, to add later on bits of configurations, perhaps meant only when `visual-regexp` gets loaded.

My code, although based on that, does not explicitly load it, 
```
(use-package visual-regexp-steroids
  :load-path "el-get/visual-regexp-steroids"
  :init
  (setq vr/match-separator-use-custom-face t)
  :bind (("C-c r" . vr/replace)
	 ("C-c q" . vr/query-replace)
	 ("M-%"   . vr/query-replace)
	 ("C-c m" . vr/mc-mark)
	 ("C-r"   . vr/isearch-backward)
	 ("C-s"   . vr/isearch-forward)))
```

Note: I use `el-get` to install packages, but then load them via `:load-path` option (instead of relying on `el-get-bundle`, etc. That helps me save a few more seconds on startup.

**Comment by benma** [comment]
Thanks.

@alamaison, does that help?

**Comment by alamaison** [comment]
I'm not sure because since the latest update I've not been able to use visual-regexp-steroids at all.  I've opened another issue for that: #19

**Comment by benma** [comment]
@alamaison now that this issue is fixed, can you revisit this? Does @priyadarshan's solution work for you?

**Comment by alamaison** [comment]
@benma Everything seems to be working on the latest version. Thanks

**Comment by anderso** [comment]
I had a very similar problem using `elpaca` with `elpaca-use-package-mode` and `use-package-always-ensure`. This declaration results in emacs regex syntax:

```elisp
(use-package visual-regexp-steroids)
```

Whereas this declaration:

```elisp
(use-package visual-regexp-steroids
  :demand)
```

results in intended behavior.
