### ISSUE TITLE
Using visual-regexp-steroids programmatically

### ISSUE THREAD

**Issue by priyadarshan** [benma/visual-regexp-steroids.el#18]
I know that `visual` means mainly "interactive", but I was wondering if it would be possibly to use `visual-regexp-steroids` programmatically as well?

For example, would it be possible to use python syntax in regex1 (with capture groups) and regex2 (with substitution matches) below?

```
(while (re-search-forward regex1 nil t)
 (replace-match regex2))
```

Thank you so much for `visual-regexp-steroids`, it makes such a huge difference.

**Comment by benma** [comment]
Have you looked into https://github.com/joddie/pcre2el? You can convert from PCRE syntax to emacs syntax and basically use `(rxt-pcre-to-elisp regex1)` instead.

visual-regexp-steroids cannot be used for such a search/replace loop, and it would also be quiet inefficient with all the external process calls to python.

**Comment by priyadarshan** [comment]
I am converting many scripts using Python's RE advanced features. `pcre2el`, but it does not cover some PCRE features I need.
Elisp does not support Perl-style lookahead/lookbehind expressions, so  `(rxt-pcre-to-elisp regex1)`, converting to elisp's regex, won't work.
I would not mind at all slowness or inefficiencis, as long as I could use Python's RE programmatically.

**Comment by benma** [comment]
I did not have a lot of time, but it seems you might be able to abuse visual-regexp-steroids for that after all.

Something like this:

```elisp
(vr--isearch t regexp)
;; not sure if it jumps to the match automatically, it should.
;; (goto-char (nth 1 (match-data)))
(replace-match replacement)
```

Beware that vr--isearch is private and hence undocumented/unsupported, and could change in the future.

Let me know if that helps.

**Comment by benma** [comment]
I did not have a lot of time, but it seems you might be able to abuse visual-regexp-steroids for that after all.

Something like this:

```elisp
(while (vr--isearch t regex1)
 (replace-match regex2))
```

Beware that vr--isearch is private and hence undocumented/unsupported, and could change in the future.

Let me know if that helps.

**Comment by priyadarshan** [comment]
Thank you somuch for your help and time.

In the scratch buffer I tried with 
```
(setq regex1 "test")
(vr--isearch t regex1)
test
```
But I get
```
Debugger entered--Lisp error: (args-out-of-range [nil] 31)
```
I thought it was becasue my defualt pyhton is 3, so I set up `vr/command-python` to python2, with no difference.

**Comment by benma** [comment]
I copy pasted your code, it works for me. Messageline reports `241 (#o361, #xf1, ?ñ)`, which is the position of "test".

For me, doing it in the scratch buffer with interactive evaluation does not actually move the point to the result, but doing with `eval-expression` does it, so i should work in a script.

What's your emacs version and platform? Also set the variable `debug-on-error` to `t`, maybe it will yield more information.

**Comment by priyadarshan** [comment]
I have been using Emacs 25.1, but I have just downloaded Emacs 24.5, with an empty `.emacs.d` beside melap setup and `visual-regexp-steroids`, and activated `debug-on-error`.

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
```

In `*Messages*` buffer I get `mapc: Args out of range: [nil], 31`, in `*Backtrace*` buffer I get:

```
Debugger entered--Lisp error: (args-out-of-range [nil] 31)
  #[(el) "\211@	A@\306	8\307	8\310U\203)\n\310V\203)\n\nS\237I\210\311
\fBB\211-\207" [el --cl-var-- i j begin end 2 3 0 nil matches-vec cur-match] 4]((32 0 827 831))
  mapc(#[(el) "\211@	A@\306	8\307	8\310U\203)\n\310V\203)\n\nS\237I\210\311
\fBB\211-\207" [el --cl-var-- i j begin end 2 3 0 nil matches-vec cur-match] 4] ((32 0 827 831)))
  vr--isearch(t "test")
  eval((vr--isearch t regex1) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

My current system is OS X 10.10.5:
```
uname -a
                                                                                                                                                  
Darwin compute.internal 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
```
Python as seen by Emacs,
```
(shell-command "python --version")
;; Python 2.7.11
```
Although, default python from shell is 3. 4.4

**Comment by priyadarshan** [comment]
I have also tried with Python 3.3.4:
```
$ /opt/local/bin/python --version
Python 3.4.4
```
In Emacs
```
(setq vr--command-python-default "/opt/local/bin/python")
```
With same results.

**Comment by priyadarshan** [comment]
On my Ubuntu and FreeBSD machines your code runs perfectly fine, so it must be something to do with my OS X setup.

Thank you very much for your time and your code.
It is very helpful to be able to call `visual-regexp-steroids` programmatically.
This is one of the main packages in my toolchain, and I always advice people to use it.
Thank you!

**Comment by benma** [comment]
Thanks for the kind words.
