### ISSUE TITLE
Failling in *Packages* buffer

### ISSUE THREAD

**Issue by xiaoxinyi** [benma/visual-regexp-steroids.el#21]
`M-x package-list-packages`
In `*Packages*` buffer, cannot use `vr/isearch-forward` or `vr/isearch-backward`.

**Comment by benma** [comment]
Thanks. It works for me. Please specify.

**Comment by xiaoxinyi** [comment]
@benma It works fine in other buffer. But in `*Packages*` buffer, I run `M-x vr/isearch-forward` type just a character `r`, it mark all `r`s in this buffer, but message `Failing regrex I-search`.  I also cannot forward to next.

**Comment by benma** [comment]
This also works for me. What is your Emacs version? Did you try with `emacs -q`, i.e. not loading any other packages?

**Comment by xiaoxinyi** [comment]
@benma  I work on `GNU Emacs 25.1.1` .

It's my configuration : 
```
(use-package visual-regexp
  :ensure t
  :init (use-package visual-regexp-steroids
          :ensure t)
  :bind* (
          ("C-c r" . vr/replace)
          ("C-c q" . vr/query-replace)
          ("C-c m" . vr/mc-mark)
          ("C-M-s" . vr/isearch-forward)
          ("C-M-r" . vr/isearch-backward))

  )
```

**Comment by xiaoxinyi** [comment]
@benma  I use `emacs -q` to initialize only two packages. It works fine.

**Comment by benma** [comment]
This means that some other configuration of yours is interfering. Please bisect and report back :)

**Comment by xiaoxinyi** [comment]
```
script failed:Traceback (most recent call last):
  File "~/.emacs.d/elpa/visual-regexp-steroids-20160516.1238/regexp.py", line 61, in <module>
    region = sys.stdin.read()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 156398: invalid start byte
 [2 times]
script failed:Traceback (most recent call last):
  File "~/.emacs.d/elpa/visual-regexp-steroids-20160516.1238/regexp.py", line 61, in <module>
    region = sys.stdin.read()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 156398: invalid start byte
 [2 times]
```
This is the  error message.

**Comment by benma** [comment]
Thanks. Did I understand correctly that with emacs -q, there is no error? 

If you can extract and paste the contents of your packages buffer, maybe we can see what utf8 problem there is.

**Comment by xiaoxinyi** [comment]
@benma No problem with `emacs -q`.

**Comment by benma** [comment]
Ok, then please find the configuration that breaks it. 

Does `vr/replace` work, or is it just isearch?

Does it work in other buffers?

**Comment by xiaoxinyi** [comment]
@benma Thanks. `vr/replace` works well in other buffers.

**Comment by xiaoxinyi** [comment]
@benma How can I configure `python3` to run `regexp.py`?

**Comment by benma** [comment]
`M-x customize-group [ret] visual-regexp`, to modify the `vr/command-python` variable.

**Comment by benma** [comment]
> @benma No problem with emacs -q.

I assume we can close this issue then, right?
