### ISSUE TITLE
Modifiers not working as expected

### ISSUE THREAD

**Issue by ghost** [benma/visual-regexp-steroids.el#25]
Looking at prior issues, I expected that MULTILINE would be enabled by default, but mine isn't. However, even when I do enable it, it doesn't seem to affect my multiline setting. When I `C-M-s` `asdf` `C-c i`, the last keystroke just breaks me out of the regexp search state.

```

;; visual regexp steroids
(require 'visual-regexp-steroids)
(define-key global-map (kbd "C-c r") 'vr/replace)
(define-key global-map (kbd "C-c q") 'vr/query-replace)
;; if you use multiple-cursors, this is for you:
(define-key global-map (kbd "C-c m") 'vr/mc-mark)
;; to use visual-regexp-steroids's isearch instead of the built-in regexp isearch, also include the following lines:
(define-key esc-map (kbd "C-r") 'vr/isearch-backward) ;; C-M-r
(define-key esc-map (kbd "C-s") 'vr/isearch-forward) ;; C-M-s



vr/default-regexp-modifiers is a variable defined in ‘visual-regexp-steroids.el’.
Its value is (:I nil :M t :S nil :U nil)

Documentation:
Modifiers that are applied by default. All modifiers are: ’(I M S U).
See also: http://docs.python.org/library/re.html#re.I

You can customize this variable.

[back]


vr--regexp-modifiers is a variable defined in ‘visual-regexp-steroids.el’.
Its value is nil

Documentation:
Modifiers in use.

[back]



GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
```

**Comment by benma** [comment]
The modifiers, default modifiers and the keys to enable/disable them only work in `vr/replace`, `vr/query-replace` and `vr/mc-mark`, but not in `vr/isearch-forward`. To achieve the same in isearch, you can manually add them, e.g. by searching for `(?im)asdf` (enabling case insensitive and multiline search).

**Comment by ghost** [comment]
Thanks, that works great!

Why doesn't `vr/isearch-forward` respect the modifiers? Is there a way I can make `vr/isearch-forward` adhere to them?

**Comment by benma** [comment]
It's because there is no easy way to enable/disable them during search (as you saw, you exit the search when you hit any key). At least I think that was the reason, it's been a while :)

**Comment by ghost** [comment]
I see. Thanks!
